### ISSUE TITLE
Конфигурация postgres

### ISSUE THREAD

**Issue by smbdsbrain** [Lovenkrantz/napoleon-test#1]
```
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
```
Хорошей практикей будет проименовать volume с данными в postgres, для дальнейшего обслуживания.
